version: "3"

services:

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000


  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 8080:8080
    environment:
      - BACKEND_URL=http://backend:3000
